### ISSUE TITLE
Update sea ice climatology

### ISSUE THREAD

**Issue by rgrumbine** [rgrumbine/concentration#29]
The current climatology was released in 2013/14 -- TN 322. Robert W. Grumbine: 2014: [CFSR 30-Year Sea Ice Concentration Climatology](https://polar.ncep.noaa.gov/mmab/papers/tn322/) -- making it quite old, especially considering the extraordinary changes in Arctic ice cover from 2007 to present.

Because 2007 was such a discontinuity, the next climatology should start from then. For CPC purposes, it is useful to divide in to terciles of 'above', 'normal', 'below', so a multiple of 3 years should be used. 15 years is 2007-2021, 18 years requires to the end of 2024.

**Comment by sanAkel** [comment]
@rgrumbine, following our previous conversations, as agreed, data from the [OSTIA](https://data.marine.copernicus.eu/product/SST_GLO_SST_L4_NRT_OBSERVATIONS_010_001/description) system:
- SST
- Sea ice concentration, which is from [OSI-SAF](https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-SST-PUM-010-001.pdf)

will suffice. 

Factoring ⬆️ and the fact that we tend to compare our answers with the [ERA5 reanalysis](https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5), 
1. I downloaded ERA5 SST and sea ice concentration, which is essentially OSTIA SST and sea ice concentration respectively, [see Sec 6.2 of Hersbach et al., 2019](https://rmets.onlinelibrary.wiley.com/doi/10.1002/qj.3803). 
2. Produced a daily climatology using data from 2007- 2021; as already noted, 18-year version can not be produced until end of 2024.

Anyone who has access to the [MSU (orion/hercules)](https://www.hpc.msstate.edu/computing/hpc.php) can find climatologies in following paths:
✅ SST: `/home/santa/marine/data/era5/clim/e5_SSTK*.nc`
✅ Ice concentration: `/home/santa/marine/data/era5/ICE/clim/e5_CI*.nc`

cc: @NeilBarton-NOAA, @LydiaStefanova-NOAA, @SulagnaRay-NOAA 

**Note**: If _someone_ (outside of the [NOAA-EMC](https://github.com/orgs/NOAA-EMC/people)) wants to access the ⬆️ mentioned climatologies, contact [me](https://github.com/sanAkel/).

**Comment by sanAkel** [comment]
@rgrumbine since we have the data, closing this issue. If something is missing, please reopen.

**Comment by sanAkel** [comment]
FWIW, the same data is also at RDHPCS. See ⬇️ path.

` /scratch2/NCEPDEV/marine/Santha.Akella/data/era5/clim-2007-2021/`
